version: '3'
services:
  db:
    image: postgres:13.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dockertest
      PGDATA: /var/lib/postgresql/data
    restart: always
  app:
    image: nicemandocker/web-server
    container_name: application
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    